<?php

namespace App\DataFixtures;

use App\Entity\Music;
use Doctrine\Bundle\FixturesBundle\Fixture;
use Doctrine\Persistence\ObjectManager;

class MusicFixtures extends Fixture
{

    const MUSIC = [
        ['Alchemy20020','<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/732838702&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/mrsamplec2" title="Mr Sample C2" target="_blank" style="color: #cccccc; text-decoration: none;">Mr Sample C2</a> · <a href="https://soundcloud.com/mrsamplec2/alchemy20020" title="Alchemy20020" target="_blank" style="color: #cccccc; text-decoration: none;">Alchemy20020</a></div>'],
        ['SupaDance3000','<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/608350368&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/mr-sample" title="Mr Sample" target="_blank" style="color: #cccccc; text-decoration: none;">Mr Sample</a> · <a href="https://soundcloud.com/mr-sample/supadance3000" title="SupaDance3000" target="_blank" style="color: #cccccc; text-decoration: none;">SupaDance3000</a></div>'],
        ['EvoL','<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/484828743&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/mr-sample" title="Mr Sample" target="_blank" style="color: #cccccc; text-decoration: none;">Mr Sample</a> · <a href="https://soundcloud.com/mr-sample/evol" title="EvoL" target="_blank" style="color: #cccccc; text-decoration: none;">EvoL</a></div>'],
        ['Up side Down','<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/268106115&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/mr-sample" title="Mr Sample" target="_blank" style="color: #cccccc; text-decoration: none;">Mr Sample</a> · <a href="https://soundcloud.com/mr-sample/up-side-down" title="Up side Down" target="_blank" style="color: #cccccc; text-decoration: none;">Up side Down</a></div>'],
        ['Drums don\'t care','<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/716246551&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/mrsamplec2" title="Mr Sample C2" target="_blank" style="color: #cccccc; text-decoration: none;">Mr Sample C2</a> · <a href="https://soundcloud.com/mrsamplec2/drums-dont-care" title="Drums don&#x27;t care" target="_blank" style="color: #cccccc; text-decoration: none;">Drums don&#x27;t care</a></div>'],
        ['Organicus','<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/163276841&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/mr-sample" title="Mr Sample" target="_blank" style="color: #cccccc; text-decoration: none;">Mr Sample</a> · <a href="https://soundcloud.com/mr-sample/organicus" title="Organicus" target="_blank" style="color: #cccccc; text-decoration: none;">Organicus</a></div>'],
        ['Georges Brassens - Chanson Pour L\'auvergnat (Mr Sample Remix)','<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/140089648&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/mr-sample" title="Mr Sample" target="_blank" style="color: #cccccc; text-decoration: none;">Mr Sample</a> · <a href="https://soundcloud.com/mr-sample/georges-brassens-chanson-pour" title="Georges Brassens - Chanson Pour L&#x27;auvergnat (Mr Sample Remix)" target="_blank" style="color: #cccccc; text-decoration: none;">Georges Brassens - Chanson Pour L&#x27;auvergnat (Mr Sample Remix)</a></div>'],
        ['Everyday','<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/216019310&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/mr-sample" title="Mr Sample" target="_blank" style="color: #cccccc; text-decoration: none;">Mr Sample</a> · <a href="https://soundcloud.com/mr-sample/everyday" title="Everyday" target="_blank" style="color: #cccccc; text-decoration: none;">Everyday</a></div>'],
    ];

    public function load(ObjectManager $manager)
    {
        for ($i=0; $i < count(self::MUSIC); $i++) {
            $music[$i] = new Music();
            $music[$i]->setTitle(self::MUSIC[$i][0])
                ->setLink(self::MUSIC[$i][1])
                ->setCreatedAt(date_create('now'));
            $manager->persist($music[$i]);
        }

        $manager->flush();
    }
}
